DELIMITER ;;
CREATE TRIGGER TRG_INSERT_DEVICE
AFTER INSERT 
ON DEVICE
FOR EACH ROW
BEGIN

INSERT INTO TEST_RUN (TEST_JOB_ID,DEVICE_ID) SELECT TESTJOB_ID,NEW.DEVICE_ID from TEST_JOB where auto_create_on_new_device=1 and STATUS <> 'COMPLETED';

END ;;
DELIMITER ;
